### ISSUE TITLE
Object variable or With block variable not set

### ISSUE THREAD

**Issue by PManishP** [Sven-Bo/run-sql-queries-in-excel#1]
Hi, Thanks for the video tutorial. I downloded the excel file and the SQL query

Object variable or With block variable not set

Also, pyhton, anaconda, xlwings and xlwings addin are installed on my system.

Can you suggest why this issue appeared in your excel with no changes made personally.

Best regards,
Manish

**Comment by Sven-Bo** [comment]
Which xlwings version are you using?

**Comment by PManishP** [comment]
Xlwings version is 0.27.15. Hope this helps.

**Comment by Sven-Bo** [comment]
I cannot replicate the issue in a virtual env with 0.27.15.
Hence, I am closing the issue as I do not have a solution.
